/**
 * T-MIG-051 seed — the replay-state recipe for the w3 rich-200 golden family
 * (N-4 capture half). Two-stage, because the state is built IN PARTNERSHIP
 * with the cases themselves:
 *
 *   --stage accounts  (pass 1 setup)
 *       0. the frozen Flyway seed posture (golden/cases/files/t51-seed.sql:
 *          the V2/V6/V7/V63 data rows dumped from a local frozen-core boot)
 *          when the db has no seed questions yet, + the V1 role registry and
 *          the V19 one-time bootstrap window row (the drizzle baseline is
 *          schema-only)
 *       1. bootstrap-admin claim (one-time first-admin window; ADMIN+TEACHER)
 *       2. register the student (displayName "User 1" — the scrubbed identity
 *          the cases pin; .invalid email, synthetic)
 *       NO ingests: the w3-sme-ingest-rich-200 (seq 10) and
 *       w3-sme-ingest-replace-rich-200 (seq 11) cases ARE the ingests —
 *       seeding them here would make the case replay a THIRD ingest
 *       (deactivated:2 vs the pinned 0) and double the status mappings.
 *
 *   --stage attempts  (pass 2 setup; run AFTER the sme pass)
 *       3. the two STRUCTURED attempts by the student on the ingested
 *          question (part ids resolved from the database — they are
 *          ingest-generated by the case replays)
 *       4. FORCE the N-4 exhibit: both attempt ids renamed to the constants
 *          the cases pin (copy + re-point + delete — answers→attempts is ON
 *          DELETE CASCADE / ON UPDATE NO ACTION / NOT deferrable, byte-matched
 *          by the drizzle baseline), then both created_at set to the SAME
 *          instant — the tie that routes the within-paper comparator into the
 *          attempt-id tie-break, where the java.util.UUID.compareTo SIGNED
 *          law (uuidCompare) is under test. The constants deliberately
 *          reverse their unsigned/hex order so the pre-fix string-lex port
 *          FAILS the case and the signed comparator passes it.
 *
 *   --stage all       (legacy one-shot for capture environments; NOT for the
 *                      golden replay split — it includes the two ingests)
 *
 * Usage:
 *   bun golden/tools/seed-t51-rich200.ts --target <url> --database-url <pg> \
 *     [--stage accounts|attempts|all]
 * Prints ADMIN_TOKEN=... / STUDENT_TOKEN=... last; feed the admin token to
 * the runner (the bootstrap claimant is ADMIN+TEACHER — it passes every
 * marking + admin surface):
 *   bun golden/runner.ts --target <url> --token <jwt> --filter <family>
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import postgres from "postgres";

const args = process.argv.slice(2);
function arg(name: string): string {
  const i = args.indexOf(name);
  if (i < 0) throw new Error(`missing ${name}`);
  return args[i + 1]!;
}
const target = arg("--target");
const databaseUrl = arg("--database-url");
const stage = args.includes("--stage") ? args[args.indexOf("--stage") + 1]! : "all";
if (!["accounts", "attempts", "all"].includes(stage)) {
  throw new Error(`unknown stage ${stage}`);
}

const CORPUS = join(import.meta.dir, "..", "cases", "files", "t51-corpus.zip");

// the constants the queue-v2 rich case's item order pins. msb 0xf0ae6395…
// is signed-NEGATIVE → sorts before 0x4e094481… (signed law); unsigned hex
// order would reverse it.
const ATTEMPT_1 = "f0ae6395-0000-4000-8000-0000000000a1";
const ATTEMPT_2 = "4e094481-0000-4000-8000-0000000000a2";
const TIED_AT = "2026-10-06T01:40:00Z";

const ADMIN_EMAIL = "t51-admin@example.invalid";
const ADMIN_PASSWORD = "t51-admin-pass-123";
const ADMIN_NAME = "User 9";
const STUDENT_EMAIL = "t51-student@example.invalid";
const STUDENT_PASSWORD = "t51-student-pass-123";
const STUDENT_NAME = "User 1"; // the scrubbed displayName the cases pin
// a TEACHER-role account so the role-gated 403 postures replay with the
// role they captured (w3-sme-status-teacher-403); join code via env —
// the same synthetic secret the capture boot used
const TEACHER_EMAIL = "t51-teacher@example.invalid";
const TEACHER_PASSWORD = "t51-teacher-pass-123";
const TEACHER_NAME = "User 8";
const TEACHER_JOIN_CODE = process.env.SYLLABAI_TEACHER_JOIN_CODE ?? "";

const sql = postgres(databaseUrl);

async function api(
  path: string,
  init: RequestInit & { token?: string } = {},
): Promise<Response> {
  const headers: Record<string, string> = { ...(init.headers as Record<string, string>) };
  if (init.token) headers.Authorization = `Bearer ${init.token}`;
  const res = await fetch(new URL(path, target), { ...init, headers });
  if (!res.ok) {
    throw new Error(`${path} -> ${res.status}: ${(await res.text()).slice(0, 300)}`);
  }
  return res;
}

async function login(email: string, password: string): Promise<string> {
  return (
    await (
      await api("/api/v1/auth/login", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ email, password }),
      })
    ).json()
  ).accessToken;
}

let adminToken: string;
let studentToken: string;
let teacherToken: string;

if (stage === "accounts" || stage === "all") {
  // ── 0. the frozen Flyway seed posture (skip when already seeded) ──────────
  const existing = await sql`select count(*) as n from questions where external_ref like 'SEED-%'`;
  if ((existing[0] as { n: string }).n === "0") {
    await sql.unsafe(readFileSync(join(import.meta.dir, "..", "cases", "files", "t51-seed.sql"), "utf8"));
    console.log("seed posture applied (t51-seed.sql)");
  } else {
    console.log("seed posture already present; skipped");
  }
  // the V1 role registry + the V19 one-time bootstrap window row (the
  // drizzle baseline is schema-only; both are Flyway DATA)
  await sql`insert into roles (name, description) values
    ('STUDENT', 'Learner account — self-registered'),
    ('TEACHER', 'Teacher account — provisioned by an admin'),
    ('ADMIN', 'Administrator — full control')
    on conflict (name) do nothing`;
  await sql`insert into bootstrap_admin_state (id) values (1) on conflict (id) do nothing`;

  // ── 1. bootstrap-admin claim (one-time window; ADMIN+TEACHER shape) ──────
  const bootStatus = (await (await api("/api/v1/auth/bootstrap-status")).json()) as {
    available?: boolean;
  };
  if (bootStatus.available === true) {
    adminToken = (
      await (
        await api("/api/v1/auth/bootstrap-admin", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({
            email: ADMIN_EMAIL,
            password: ADMIN_PASSWORD,
            displayName: ADMIN_NAME,
          }),
        })
      ).json()
    ).accessToken;
    console.log("bootstrap-admin claimed");
  } else {
    throw new Error(
      `bootstrap window not available (${JSON.stringify(bootStatus)}) — run against a FRESH db`,
    );
  }

  // ── 2. the student ────────────────────────────────────────────────────────
  const reg = await fetch(new URL("/api/v1/auth/register", target), {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      email: STUDENT_EMAIL,
      password: STUDENT_PASSWORD,
      displayName: STUDENT_NAME,
      role: "STUDENT",
    }),
  });
  if (!reg.ok && reg.status !== 409) {
    throw new Error(`register -> ${reg.status}: ${await reg.text()}`);
  }
  studentToken = await login(STUDENT_EMAIL, STUDENT_PASSWORD);
  console.log("student ready (User 1)");

  // the TEACHER-role account (403-posture replay token)
  const treg = await fetch(new URL("/api/v1/auth/register", target), {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      email: TEACHER_EMAIL,
      password: TEACHER_PASSWORD,
      displayName: TEACHER_NAME,
      role: "TEACHER",
      joinCode: TEACHER_JOIN_CODE,
    }),
  });
  if (!treg.ok && treg.status !== 409) {
    throw new Error(`teacher register -> ${treg.status}: ${await treg.text()}`);
  }
  teacherToken = await login(TEACHER_EMAIL, TEACHER_PASSWORD);
  console.log("teacher ready (User 8)");
} else {
  adminToken = await login(ADMIN_EMAIL, ADMIN_PASSWORD);
  studentToken = await login(STUDENT_EMAIL, STUDENT_PASSWORD);
  teacherToken = await login(TEACHER_EMAIL, TEACHER_PASSWORD);
  console.log("accounts logged in (existing db)");
}

if (stage === "accounts") {
  await sql.end();
  console.log(`\nADMIN_TOKEN=${adminToken}`);
  console.log(`STUDENT_TOKEN=${studentToken}`);
  console.log(`TEACHER_TOKEN=${teacherToken}`);
  console.log("next: bun golden/runner.ts --target <url> --token <role-token> --filter <case-name-substring>");
  process.exit(0);
}

if (stage === "all") {
  // ── 3. ingest the corpus twice (legacy capture path) ──────────────────────
  const corpus = new Uint8Array(readFileSync(CORPUS));
  for (const pass of ["fresh", "replace"] as const) {
    const form = new FormData();
    form.append("file", new Blob([corpus], { type: "application/zip" }), "t51-corpus.zip");
    const summary = await (
      await api("/api/v1/admin/question-bank/ingest", {
        method: "POST",
        token: adminToken,
        body: form,
      })
    ).json();
    console.log(`ingest ${pass}:`, JSON.stringify(summary));
  }
}

// ── 3b/4. the two structured attempts on the ACTIVE ingested question ──────
const rows = await sql`
  select q.id as question_id, p.id as part_id, p.ordering
  from questions q
  join question_versions v on v.question_id = q.id
  join question_parts p on p.question_version_id = v.id
  where q.external_ref = 'T51-WCH11-002' and q.active = true
  order by p.ordering`;
if (rows.length !== 2) throw new Error(`expected 2 parts, got ${rows.length}`);
const questionId = rows[0]!.question_id as string;
const [partA, partB] = rows.map((r) => r.part_id as string);

async function structuredAttempt(textA: string, textB: string): Promise<string> {
  const res = await api("/api/v1/attempts/structured", {
    method: "POST",
    token: studentToken,
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      questionId,
      partAnswers: [
        { partId: partA, answerText: textA },
        { partId: partB, answerText: textB },
      ],
      responseTimeMs: 150000,
      confidence: 3,
      selfDoubtFlag: false,
      timedCondition: false,
    }),
  });
  return ((await res.json()) as { attemptId: string }).attemptId;
}
const real1 = await structuredAttempt("X because a", "Y because b");
const real2 = await structuredAttempt("Alt x text", "Alt y text");
console.log("attempts:", real1, real2);

// ── 5. force the N-4 exhibit: deterministic ids + the created_at tie ───────
// answers→attempts is ON DELETE CASCADE / ON UPDATE NO ACTION / NOT
// deferrable (the frozen V45 end-state, byte-matched by the drizzle
// baseline), so a rename = copy the row under the new id, re-point the
// answer rows, delete the original — one transaction.
async function renameAttempt(from: string, to: string): Promise<void> {
  const cols = (
    await sql`
      select column_name from information_schema.columns
      where table_schema = 'public' and table_name = 'attempts'
        and column_name <> 'id'
      order by ordinal_position`
  ).map((r) => r.column_name as string);
  const colList = ['"id"', ...cols.map((c) => `"${c}"`)].join(", ");
  const selList = [`'${to}'::uuid`, ...cols.map((c) => `"${c}"`)].join(", ");
  await sql.begin(async (tx) => {
    // from/to are this script's own uuid constants — no user input
    await tx.unsafe(`insert into attempts (${colList}) select ${selList} from attempts where id = '${from}'`);
    await tx`update answers set attempt_id = ${to} where attempt_id = ${from}`;
    await tx.unsafe(`delete from attempts where id = '${from}'`);
  });
}
await renameAttempt(real1, ATTEMPT_1);
await renameAttempt(real2, ATTEMPT_2);
await sql`update attempts set created_at = ${TIED_AT} where id in (${ATTEMPT_1}, ${ATTEMPT_2})`;
const check = await sql`
  select id, created_at from attempts
  where id in (${ATTEMPT_1}, ${ATTEMPT_2}) order by created_at asc, id asc`;
console.log("tied attempts:", check.map((r) => `${r.id} @ ${r.created_at?.toISOString()}`));

await sql.end();
console.log(`\nADMIN_TOKEN=${adminToken}`);
console.log("next: bun golden/runner.ts --target <url> --token <ADMIN_TOKEN> --filter w3-teacher-marking-");
