import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { PILOT } from "./helpers";

/**
 * Past-papers PDF viewer E2E (operator audit s140) — this surface previously
 * had ZERO E2E coverage: the viewer is a client-side pdf.js canvas stack, so
 * nothing else in the suite would notice a regression in rendering, find,
 * page navigation, rotation, or the mock flow's links.
 *
 * Determinism: the corpus PDFs stream from raw.githubusercontent.com — every
 * test intercepts that host and serves tests/fixtures/pp-viewer.pdf (3 text
 * pages, generated by scripts/s140_fixture_pdf.py). No network, no flaky
 * archive, real pdf.js worker + rendering pipeline.
 *
 * The axe gate mirrors a11y.spec.ts: no CRITICAL/SERIOUS violations on the
 * loaded viewer (toolbar buttons, page inputs, the focusable pages region).
 */

const PAPER_URL = `/courses/${PILOT}/past-papers/view/2019-06/4CH1-1C`;
const FIXTURE = "tests/fixtures/pp-viewer.pdf";

test.beforeEach(async ({ page }) => {
  await page.route("**/raw.githubusercontent.com/**", (route) =>
    route.fulfill({ path: FIXTURE, contentType: "application/pdf" }),
  );
});

async function readyViewer(page: import("@playwright/test").Page) {
  await page.goto(`${PAPER_URL}?doc=qp`, { waitUntil: "load" });
  // the first canvas paints once the (tiny) fixture streams + renders
  await expect(
    page.locator(".pp-pane canvas").first(),
    "the question paper paints its pages",
  ).toBeVisible({ timeout: 20_000 });
}

test("viewer: pages render, indicator reads 1 / 3, unpainted holders show ghosts", async ({ page }) => {
  await readyViewer(page);
  await expect(page.getByRole("img", { name: "Page 1 of 3" })).toBeVisible();
  await expect(page.getByRole("img", { name: "Page 3 of 3" })).toBeVisible();
  const holders = page.locator(".pp-holder");
  await expect(holders).toHaveCount(3);
  // the page input reflects page 1
  await expect(page.getByLabel("Page number of 3")).toHaveValue("1");
  // ghost labels exist for any page outside the render window (all 3 are
  // within radius on the fixture, so assert the CSS contract instead)
  const ghostCss = await page.evaluate(() => {
    for (const sheet of document.styleSheets) {
      try {
        for (const rule of sheet.cssRules) {
          if (rule.cssText.includes(".pp-holder:empty::after")) return rule.cssText;
        }
      } catch {
        /* cross-origin sheet */
      }
    }
    return null;
  });
  expect(ghostCss, "the Page-N ghost rule is compiled").toContain("attr(data-page)");
});

test("viewer: typing a page number jumps (indicator follows)", async ({ page }) => {
  await readyViewer(page);
  const input = page.getByLabel("Page number of 3");
  await input.click();
  await input.fill("3");
  await input.press("Enter");
  await input.press("Tab"); // blur — the draft then follows the tracked page
  await expect
    .poll(async () => input.inputValue(), { timeout: 10_000 })
    .toBe("3");
  // an out-of-range draft clamps to the last page
  await input.click();
  await input.fill("99");
  await input.press("Enter");
  await expect(input).toHaveValue("3");
});

test("viewer: find bar searches, highlights, and steps through matches", async ({ page }) => {
  await readyViewer(page);
  await page.getByRole("button", { name: "Find in document" }).click();
  const findInput = page.getByPlaceholder("Find in document…");
  // the fixture has "magnesium chloride" on pages 1 and 2 (2 matches)
  await findInput.fill("magnesium chloride");
  await expect
    .poll(async () => page.locator(".pp-hl").count(), { timeout: 20_000 })
    .toBeGreaterThanOrEqual(2);
  await expect(findInput).toBeFocused();
  // Enter steps to the next match (the current highlight moves)
  await findInput.press("Enter");
  await expect(page.locator(".pp-hl.pp-hl-current").first()).toBeVisible();
  // Escape closes the bar and clears the highlights
  await findInput.press("Escape");
  await expect(page.locator(".pp-hl")).toHaveCount(0);
  // reopening re-shows the live results (s140 B2 regression pin)
  await page.getByRole("button", { name: "Find in document" }).click();
  await expect
    .poll(async () => page.locator(".pp-hl").count(), { timeout: 10_000 })
    .toBeGreaterThanOrEqual(2);
});

test("viewer: rotate 90° swaps the page aspect and keeps painting", async ({ page }) => {
  await readyViewer(page);
  const pane = page.locator(".pp-pane").first();
  await expect(pane).toHaveAttribute("data-rot", "0");
  const holder = page.getByRole("img", { name: "Page 1 of 3" });
  const before = (await holder.boundingBox())!;
  expect(before.height).toBeGreaterThan(before.width); // A4 portrait
  await page.getByRole("button", { name: /Rotate 90 degrees/ }).click();
  await expect(pane).toHaveAttribute("data-rot", "90");
  const after = (await holder.boundingBox())!;
  expect(after.width, "rotated holder is landscape").toBeGreaterThan(after.height);
  // the canvas survives the rotation re-render (double-buffered)
  await expect(page.locator(".pp-pane canvas").first()).toBeVisible();
  await page.getByRole("button", { name: /Rotate 90 degrees/ }).click();
  await page.getByRole("button", { name: /Rotate 90 degrees/ }).click();
  await page.getByRole("button", { name: /Rotate 90 degrees/ }).click();
  await expect(pane).toHaveAttribute("data-rot", "0");
});

test("viewer: zoom ladder shows honest round steps and resets", async ({ page }) => {
  await readyViewer(page);
  const zoomIn = page.getByRole("button", { name: "Zoom in" });
  const zoomOut = page.getByRole("button", { name: "Zoom out" });
  const reset = page.getByRole("button", { name: "Reset zoom" });
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 100% of fit width");
  // s141: the ladder descends below fit-width — zoom-out is live at 100%
  await expect(zoomOut).toBeEnabled();
  await zoomIn.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 125% of fit width");
  await zoomIn.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 150% of fit width");
  await reset.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 100% of fit width");
  // the below-fit overview steps (s141 75/50 + s142's 25% thumbnail floor,
  // where the button disables)
  const holder = page.getByRole("img", { name: "Page 1 of 3" });
  const fitW = (await holder.boundingBox())!.width;
  await zoomOut.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 75% of fit width");
  await zoomOut.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 50% of fit width");
  await zoomOut.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 25% of fit width");
  await expect(zoomOut).toBeDisabled();
  // the page physically shrinks to ~a quarter width (centered via mx-auto)
  // and the canvas survives the refit (double-buffered — never blanks)
  await expect
    .poll(async () => (await holder.boundingBox())?.width, { timeout: 5_000 })
    .toBeLessThan(fitW * 0.45);
  await expect(page.locator(".pp-pane canvas").first()).toBeVisible();
  // reset is enabled while BELOW fit (the old <= floor kept it disabled)
  await expect(reset).toBeEnabled();
  await reset.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 100% of fit width");
  await expect(zoomOut).toBeEnabled();
});

test("viewer: fit-page preset frames the whole page inside the scroller", async ({ page }) => {
  await readyViewer(page);
  const holder = page.getByRole("img", { name: "Page 1 of 3" });
  const region = page.locator(".pp-pane [role='region']");
  const zoomIn = page.getByRole("button", { name: "Zoom in" });
  const fitWidth = page.getByRole("button", { name: "Fit width" });
  const fitPage = page.getByRole("button", { name: "Fit page" });
  // default: fit-width is the pressed base, the A4 page is TALLER than the pane
  await expect(fitWidth).toHaveAttribute("aria-pressed", "true");
  await expect(fitPage).toHaveAttribute("aria-pressed", "false");
  const regionBox = (await region.boundingBox())!;
  const wideBox = await holder.boundingBox();
  expect(wideBox!.height).toBeGreaterThan(regionBox.height);
  // s142: switching the base frames the WHOLE page, zoom resets to 100%, and
  // the toolbar names the new base honestly
  await fitPage.click();
  await expect(fitPage).toHaveAttribute("aria-pressed", "true");
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 100% of fit page");
  await expect
    .poll(async () => (await holder.boundingBox())?.height, { timeout: 5_000 })
    .toBeLessThanOrEqual(regionBox.height + 1);
  const pageBox = await holder.boundingBox();
  expect(pageBox!.height, "fit-page shrank the page vs fit-width").toBeLessThan(wideBox!.height);
  expect(pageBox!.x, "the framed page centers (mx-auto)").toBeGreaterThan(wideBox!.x + 40);
  // the canvas re-rendered at the new scale (double-buffered, never blank)
  await expect(page.locator(".pp-pane canvas").first()).toBeVisible();
  // zoom still steps the ladder on the new base, honestly labelled
  await zoomIn.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 125% of fit page");
  // and back: fit-width restores the wide base and its honest title
  await fitWidth.click();
  await expect(fitWidth).toHaveAttribute("aria-pressed", "true");
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 100% of fit width");
  await expect
    .poll(async () => (await holder.boundingBox())?.width, { timeout: 5_000 })
    .toBeGreaterThan(pageBox!.width);
});

test("viewer: split view shows QP and MS panes side by side", async ({ page }) => {
  await page.goto(`${PAPER_URL}?doc=split`, { waitUntil: "load" });
  const panes = page.locator(".pp-pane");
  await expect(panes).toHaveCount(2);
  for (const pane of await panes.all()) {
    await expect(pane.locator("canvas").first()).toBeVisible({ timeout: 20_000 });
  }
  // s140 audit regression pin: the split grid's implicit row used to grow to
  // the full document height — panes never bounded their scrollers, the
  // VISIBLE pages stayed blank and canvases rendered ~14 pages down.
  const state = await page.evaluate(() =>
    [...document.querySelectorAll(".pp-pane")].map((p) => {
      const scroller = p.querySelector("[role='region']");
      return {
        scrollerH: scroller ? Math.round(scroller.getBoundingClientRect().height) : 0,
        firstPagePainted: (p.querySelector(".pp-holder")?.childElementCount ?? 0) > 0,
      };
    }),
  );
  expect(state, "two panes inspected").toHaveLength(2);
  for (const s of state) {
    expect(s.scrollerH, "split scroller is viewport-bounded, not document-height").toBeLessThan(2000);
    expect(s.firstPagePainted, "the visible first page holds a canvas").toBe(true);
  }
});

test("viewer: two-page spread pairs facing pages side by side", async ({ page }) => {
  await readyViewer(page);
  const spreadBtn = page.getByRole("button", { name: "Two-page spread" });
  // the default Desktop Chrome viewport (1280x720) leaves the pane wide
  // enough to offer the layout (spread gates on PANE width, not viewport)
  await expect(spreadBtn).toBeVisible();
  await expect(spreadBtn).toHaveAttribute("aria-pressed", "false");
  const singleBox = (await page.getByRole("img", { name: "Page 1 of 3" }).boundingBox())!;
  expect(singleBox.width).toBeGreaterThan(400); // fit-width sanity anchor
  await spreadBtn.click();
  await expect(spreadBtn).toHaveAttribute("aria-pressed", "true");
  // 3 pages pair into two rows: [1|2] and [3]
  await expect(page.locator("[data-spread-row]")).toHaveCount(2);
  // both mates of the first row paint (the render window covers them)
  await expect
    .poll(async () => page.locator(".pp-pane canvas").count(), { timeout: 10_000 })
    .toBeGreaterThanOrEqual(2);
  const p1 = (await page.getByRole("img", { name: "Page 1 of 3" }).boundingBox())!;
  const p2 = (await page.getByRole("img", { name: "Page 2 of 3" }).boundingBox())!;
  expect(p1.width, "each mate fits half the pane").toBeLessThan(singleBox.width * 0.6);
  expect(p2.x, "page 2 sits to the right of its mate").toBeGreaterThan(p1.x + p1.width - 2);
  // the toolbar names the halved base honestly
  await expect(page.getByRole("button", { name: "Zoom in" })).toHaveAttribute(
    "title",
    "Zoom: 100% of spread width",
  );
  // back to single: the rows dissolve and a canvas stays alive
  await spreadBtn.click();
  await expect(page.locator("[data-spread-row]")).toHaveCount(0);
  await expect(spreadBtn).toHaveAttribute("aria-pressed", "false");
  await expect(page.locator(".pp-pane canvas").first()).toBeVisible();
});

test("viewer: the viewing setup persists across papers", async ({ page }) => {
  await readyViewer(page);
  // assemble a distinctive setup: fit-page + 125% + 90° + spread. Order
  // matters — switching the fit base resets the zoom, so zoom AFTER.
  await page.getByRole("button", { name: "Fit page" }).click();
  await page.getByRole("button", { name: "Zoom in" }).click();
  await page.getByRole("button", { name: /Rotate 90 degrees/ }).click();
  await page.getByRole("button", { name: "Two-page spread" }).click();
  const pane = page.locator(".pp-pane").first();
  const spreadBtn = page.getByRole("button", { name: "Two-page spread" });
  await expect(pane).toHaveAttribute("data-rot", "90");
  await expect(spreadBtn).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator("[data-spread-row]")).toHaveCount(2);
  await expect(page.getByRole("button", { name: "Zoom in" })).toHaveAttribute(
    "title",
    "Zoom: 125% of fit page",
  );
  // a DIFFERENT paper of the same course restores the whole setup (the
  // fixture intercept serves the same 3-page PDF for any raw corpus URL)
  await page.goto(`${PAPER_URL.replace("2019-06", "2026-06")}?doc=qp`, { waitUntil: "load" });
  await expect(page.locator(".pp-pane canvas").first()).toBeVisible({ timeout: 20_000 });
  await expect(pane).toHaveAttribute("data-rot", "90");
  await expect(page.getByRole("button", { name: "Fit page" })).toHaveAttribute(
    "aria-pressed",
    "true",
  );
  await expect(page.getByRole("button", { name: "Zoom in" })).toHaveAttribute(
    "title",
    "Zoom: 125% of fit page",
  );
  await expect(spreadBtn).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator("[data-spread-row]")).toHaveCount(2);
  // narrowing the viewport below the pane threshold auto-offs the LAYOUT…
  await page.setViewportSize({ width: 500, height: 800 });
  await expect(spreadBtn).toBeHidden({ timeout: 5_000 });
  await expect(page.locator("[data-spread-row]")).toHaveCount(0);
  // …without erasing the choice — widening re-pairs the pages
  await page.setViewportSize({ width: 1280, height: 720 });
  await expect(spreadBtn).toBeVisible({ timeout: 5_000 });
  await expect(spreadBtn).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator("[data-spread-row]")).toHaveCount(2);
});

test("mock: 'Just view the paper' lands on the viewer (s140 B1 404 pin)", async ({ page }) => {
  await page.goto(`${PAPER_URL}?mode=mock`, { waitUntil: "load" });
  await page.getByRole("link", { name: "Just view the paper" }).click();
  await expect(page).toHaveURL(new RegExp(`/past-papers/view/2019-06/4CH1-1C`));
  await expect(page.locator(".pp-pane canvas").first()).toBeVisible({ timeout: 20_000 });
});

test("viewer: the loaded page has no serious or critical axe violations", async ({ page }) => {
  await readyViewer(page);
  const results = await new AxeBuilder({ page }).analyze();
  const serious = results.violations.filter(
    (v) => v.impact === "critical" || v.impact === "serious",
  );
  for (const v of serious) {
    console.error(`[axe:pp-viewer] ${v.id} (${v.impact}) x${v.nodes.length}: ${v.help}`);
  }
  expect(serious, "pp-viewer: serious/critical a11y violations").toEqual([]);
});
