#!/usr/bin/env python3
"""
T-MIG-092 chain: live-deploy step — apply the r1c-precedented worktree-only
deploy shims to the session clone (upstream repo untouched; files restored
after build), bundle apps/api to a single Node-target file, and stage the
Vercel deploy shape of record.

Shim v2 (this iteration): the 6 hash-pinned concept-graph YAMLs are INLINED
into the bundle via a generated asset module — the module-scope singleton
reads them at boot (r1c's law: the Bun-only APIs are MODULE-SCOPE in the NBA
graph singleton), and bun build statically resolves import.meta.url to
source paths, so filesystem derivation cannot survive bundling. The SHA-256
pins still enforce byte integrity on the inlined bytes (same law, same
frozen error texts).
"""
import hashlib
import json
import os
import subprocess
import sys

REPO = "/tmp/syllabai-v2"
STAGE = "/tmp/api-stage"
ENTRY = f"{REPO}/apps/api/src/deploy-entry.ts"
GEN = f"{REPO}/apps/api/src/services/concept-assets.gen.ts"

ASSETS = {
    "learner-me/concepts.yaml": "apps/api/src/services/learner-me/concept-graph/concepts.yaml",
    "learner-me/concept_edges.yaml": "apps/api/src/services/learner-me/concept-graph/concept_edges.yaml",
    "learner-me/practicals.yaml": "apps/api/src/services/learner-me/concept-graph/practicals.yaml",
    "teacher/concept-graph/relationships.yaml": "apps/api/src/services/teacher/concept-graph/relationships.yaml",
    "teacher/concept-graph/specification_points.yaml": "apps/api/src/services/teacher/concept-graph/specification_points.yaml",
    "teacher/concept-graph/topics.yaml": "apps/api/src/services/teacher/concept-graph/topics.yaml",
}

SHIM_BANNER = (
    "// DEPLOY-SHIM (worktree-only, r1c Wave-A precedent, upstream repo UNTOUCHED): "
    "Bun.CryptoHasher -> node:crypto createHash; Bun.YAML.parse -> js-yaml load "
    "(plain-data parity); the module-scope concept-graph singleton reads the 6 "
    "hash-pinned YAMLs from the INLINED byte-verbatim asset module "
    "(concept-assets.gen.ts) — bun build cannot preserve runtime asset paths, "
    "and the SHA-256 pins still enforce byte integrity on the inlined bytes.\n"
)


def patch(path, edits):
    src = open(path).read()
    for old, new in edits:
        assert old in src, f"pattern not found in {path}: {old[:80]!r}"
        assert src.count(old) == 1, f"pattern not unique in {path}: {old[:80]!r}"
        src = src.replace(old, new)
    open(path, "w").write(src)
    print("shimmed:", path)


def main():
    # 1. generated asset module (byte-verbatim, JS-string-escaped)
    entries = []
    for key, rel in ASSETS.items():
        data = open(f"{REPO}/{rel}", "rb").read()
        entries.append(f'  {json.dumps(key)}: {json.dumps(data.decode("utf8"))},')
        print(f"asset {key}: {len(data)} bytes sha256 {hashlib.sha256(data).hexdigest()[:16]}...")
    open(GEN, "w").write(
        "// DEPLOY-SHIM generated (worktree-only): byte-verbatim inlined copies of the\n"
        "// 6 hash-pinned concept-graph YAMLs (learner-me 043-t2 + teacher V15 substrate).\n"
        "// Keys are <band>/<classpath-relative-path>. Generated by deploy_bundle_build.py.\n"
        "export const CONCEPT_ASSETS: Record<string, string> = {\n"
        + "\n".join(entries)
        + "\n};\n"
    )
    print("wrote", GEN)

    # 2. shims
    snapshot = f"{REPO}/apps/api/src/services/teacher/snapshot.ts"
    nba = f"{REPO}/apps/api/src/services/learner-me/nba-concept-graph.ts"

    patch(
        snapshot,
        [
            (
                'import { readFileSync } from "node:fs";\nimport { join } from "node:path";',
                "import { join } from \"node:path\";\n"
                "import { createHash } from \"node:crypto\";\n"
                "import yaml from \"js-yaml\";\n"
                "import { CONCEPT_ASSETS } from \"../concept-assets.gen\";\n" + SHIM_BANNER,
            ),
            (
                "function sha256Hex(bytes: string): string {\n"
                "  const hasher = new Bun.CryptoHasher(\"sha256\");\n"
                "  hasher.update(bytes);\n"
                "  return hasher.digest(\"hex\");\n"
                "}",
                "function sha256Hex(bytes: string): string {\n"
                "  return createHash(\"sha256\").update(bytes).digest(\"hex\");\n"
                "}",
            ),
            (
                "function doc(text: string, resource: string): Record<string, unknown> {\n"
                "  const parsed = Bun.YAML.parse(text) as unknown;",
                "function doc(text: string, resource: string): Record<string, unknown> {\n"
                "  const parsed = yaml.load(text) as unknown;",
            ),
            (
                "function readResource(path: string, dir: string): string {\n"
                "  // the frozen classpath layout is concept-graph/<file>.yaml relative to the\n"
                "  // band dir — the V2 copy mirrors it under teacher/concept-graph/\n"
                "  try {\n"
                "    return readFileSync(join(dir, path), \"utf8\");\n"
                "  } catch (e) {\n"
                "    throw new Error(\"concept graph snapshot missing: \" + path);\n"
                "  }",
                "function readResource(path: string, dir: string): string {\n"
                "  // SHIM: the classpath resource rides the inlined byte-verbatim asset module\n"
                "  const text = CONCEPT_ASSETS[\"teacher/\" + path];\n"
                "  if (text === undefined) throw new Error(\"concept graph snapshot missing: \" + path);\n"
                "  return text;",
            ),
            (
                "  const learnerDir = join(teacherDir, \"../learner-me/concept-graph\");\n"
                "  const specPoints = readResource(SPEC_POINTS_RESOURCE, teacherDir);\n"
                "  const topics = readResource(TOPICS_RESOURCE, teacherDir);\n"
                "  const relationships = readResource(RELATIONSHIPS_RESOURCE, teacherDir);\n"
                "  const concepts = readFileSync(join(learnerDir, \"concepts.yaml\"), \"utf8\");\n"
                "  const conceptEdges = readFileSync(join(learnerDir, \"concept_edges.yaml\"), \"utf8\");\n"
                "  const practicals = readFileSync(join(learnerDir, \"practicals.yaml\"), \"utf8\");",
                "  const specPoints = readResource(SPEC_POINTS_RESOURCE, teacherDir);\n"
                "  const topics = readResource(TOPICS_RESOURCE, teacherDir);\n"
                "  const relationships = readResource(RELATIONSHIPS_RESOURCE, teacherDir);\n"
                "  const concepts = CONCEPT_ASSETS[\"learner-me/concepts.yaml\"];\n"
                "  const conceptEdges = CONCEPT_ASSETS[\"learner-me/concept_edges.yaml\"];\n"
                "  const practicals = CONCEPT_ASSETS[\"learner-me/practicals.yaml\"];\n"
                "  if (concepts === undefined || conceptEdges === undefined || practicals === undefined)\n"
                "    throw new Error(\"concept graph snapshot missing: learner-me/concept-graph\");",
            ),
        ],
    )

    patch(
        nba,
        [
            (
                'import { readFileSync } from "node:fs";\nimport { join } from "node:path";',
                "import { createHash } from \"node:crypto\";\n"
                "import yaml from \"js-yaml\";\n"
                "import { CONCEPT_ASSETS } from \"../concept-assets.gen\";\n" + SHIM_BANNER,
            ),
            (
                "function sha256Of(text: string): string {\n"
                "  const hasher = new Bun.CryptoHasher(\"sha256\");\n"
                "  hasher.update(text);\n"
                "  return hasher.digest(\"hex\");\n"
                "}",
                "function sha256Of(text: string): string {\n"
                "  return createHash(\"sha256\").update(text).digest(\"hex\");\n"
                "}",
            ),
            (
                "function loadSnapshotYaml(file: string, expectedSha256: string): Record<string, unknown> {\n"
                "  const resource = join(import.meta.dir, \"concept-graph\", file);\n"
                "  const text = readFileSync(resource, \"utf8\");\n"
                "  requireHash(text, expectedSha256, file);\n"
                "  return Bun.YAML.parse(text) as Record<string, unknown>;\n"
                "}",
                "function loadSnapshotYaml(file: string, expectedSha256: string): Record<string, unknown> {\n"
                "  const text = CONCEPT_ASSETS[\"learner-me/\" + file];\n"
                "  if (text === undefined) throw new Error(\"concept graph snapshot missing: learner-me/\" + file);\n"
                "  requireHash(text, expectedSha256, file);\n"
                "  return yaml.load(text) as Record<string, unknown>;\n"
                "}",
            ),
        ],
    )

    # 3. Vercel entry — explicit Node-style adapter (r1c pattern:
    # x-forwarded-proto/host + req.url reconstruction, streaming response out)
    open(ENTRY, "w").write(
        "// DEPLOY-SHIM entry (worktree-only): path-preserving Vercel Node adapter\n"
        "// for the Hono app (r1c Wave-A pattern — x-forwarded-proto/host + req.url\n"
        "// reconstruction; streaming response pass-through; hono/vercel's handle is\n"
        "// a deprecated Web-Request wrapper, unusable as a Node handler).\n"
        "import app from \"./index\";\n\n"
        "export default async function handler(req: any, res: any): Promise<void> {\n"
        "  const proto = String(req.headers[\"x-forwarded-proto\"] ?? \"https\").split(\",\")[0]!.trim();\n"
        "  const host = String(req.headers[\"x-forwarded-host\"] ?? req.headers.host ?? \"localhost\").split(\",\")[0]!.trim();\n"
        "  const url = new URL(req.url, proto + \"://\" + host).href;\n"
        "  const method = req.method ?? \"GET\";\n"
        "  const headers = new Headers();\n"
        "  for (const [k, v] of Object.entries(req.headers ?? {})) {\n"
        "    if (Array.isArray(v)) for (const x of v) headers.append(k, String(x));\n"
        "    else if (v != null) headers.set(k, String(v));\n"
        "  }\n"
        "  let body: ReadableStream<Uint8Array> | undefined;\n"
        "  const opts: any = { method, headers };\n"
        "  if (method !== \"GET\" && method !== \"HEAD\") {\n"
        "    body = new ReadableStream<Uint8Array>({\n"
        "      start(c) {\n"
        "        req.on(\"data\", (d: Buffer) => c.enqueue(new Uint8Array(d)));\n"
        "        req.on(\"end\", () => c.close());\n"
        "        req.on(\"error\", (e: Error) => c.error(e));\n"
        "      },\n"
        "    });\n"
        "    opts.body = body;\n"
        "    opts.duplex = \"half\";\n"
        "  }\n"
        "  const response = await app.fetch(new Request(url, opts));\n"
        "  const out: any = {};\n"
        "  response.headers.forEach((v, k) => {\n"
        "    out[k] = k === \"set-cookie\" ? (response.headers.getSetCookie?.() ?? v) : v;\n"
        "  });\n"
        "  res.writeHead(response.status, out);\n"
        "  if (response.body) {\n"
        "    const reader = response.body.getReader();\n"
        "    for (;;) {\n"
        "      const { done, value } = await reader.read();\n"
        "      if (done) break;\n"
        "      res.write(Buffer.from(value));\n"
        "    }\n"
        "  }\n"
        "  res.end();\n"
        "}\n"
    )
    print("wrote entry:", ENTRY)

    # 4. stage
    os.makedirs(f"{STAGE}/api", exist_ok=True)
    os.makedirs(f"{STAGE}/.vercel", exist_ok=True)
    open(f"{STAGE}/vercel.json", "w").write(
        json.dumps(
            {
                "rewrites": [
                    {"source": "/api/v1/(.*)", "destination": "/api/index"},
                    {"source": "/actuator/health", "destination": "/api/index"},
                ]
            },
            indent=2,
        )
        + "\n"
    )
    open(f"{STAGE}/.vercel/project.json", "w").write(
        json.dumps(
            {"projectId": "prj_FN5XQUMbpqKhZXFXpT80OdsKveJZ", "orgId": "team_ULL54qkhzKBmnKrpO6BD4mYX"},
            indent=2,
        )
        + "\n"
    )

    # 5. bundle
    r = subprocess.run(
        ["bun", "build", "--target=node", "--format=cjs",
         "--outfile", f"{STAGE}/api/index.js", "apps/api/src/deploy-entry.ts"],
        cwd=REPO, capture_output=True, text=True,
    )
    print(r.stdout[-1500:] if r.stdout else "", r.stderr[-1500:] if r.stderr else "")
    if r.returncode != 0:
        sys.exit("bun build failed")
    size = os.path.getsize(f"{STAGE}/api/index.js")
    print(f"bundle: {STAGE}/api/index.js {size} bytes ({size/1e6:.2f} MB)")


if __name__ == "__main__":
    main()
