"use client";

/**
 * AppShell — global chrome, SaveMyExams-style (research §4, flow crawl
 * 2026-09-19): a single header (logo · "Study tools" menu · data-mode
 * badges) and NO global sidebar. SME keeps all global navigation in the
 * header; course surfaces add exactly one course sidebar (course-shell) and
 * resource detail pages add the topic panel (resource-panel). Demo-discipline
 * disclosures and provider badges live in the footer, out of the learner's
 * reading path.
 */
import Link from "next/link";
import { usePathname } from "next/navigation";
import {
  Atom,
  BookOpen,
  BookOpenCheck,

  ChevronDown,
  CircleHelp,
  Database,
  FileQuestion,
  FlaskConical,
  GraduationCap,
  Layers,
  LayoutDashboard,
  LogIn,
  LogOut,
  Network,
  Sparkles,
  User,
  Waypoints,
  Zap,
} from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ThemeToggle } from "@/components/theme-toggle";
import { clearIdentity, useIdentity } from "@/lib/identity";
import { isImmersiveRoute } from "@/lib/focus-routes";
import { useLastOpened } from "@/lib/last-opened";
import { cn } from "@/lib/utils";
import type { PublicConfig } from "@/lib/config";
// published-graph registry, generated by scripts/kg_export.py alongside the
// bundles themselves — imported at build time so the header's context-aware
// Knowledge Graph link can never promise a slug the deployed data dir lacks
import kgDataIndex from "../../../public/kg/data/index.json";
// course registry (content/courses.json, same source lib/courses.ts serves
// from) — build-time validation so a stale last-opened slug can never send
// the header's course-scoped links at a course the deployment no longer has
import coursesRegistry from "../../../content/courses.json";

const TOOLS = [
  { href: "/dashboard", label: "Dashboard", icon: LayoutDashboard, desc: "My subjects" },
  { href: "/courses", label: "Courses", icon: GraduationCap, desc: "All Learning Hubs" },
  { href: "/revision-notes", label: "Revision Notes", icon: BookOpen },
  { href: "/exam-questions", label: "Exam Questions", icon: FileQuestion },
  { href: "/flashcards", label: "Flashcards", icon: CircleHelp },
] as const;

const MORE_TOOLS = [
  { href: "/tutor", label: "AI Tutor", icon: Sparkles },
  { href: "/assistant", label: "Assistant", icon: BookOpenCheck },
  { href: "/practice", label: "Practice", icon: Zap },
  { href: "/knowledge-graph", label: "Knowledge Graph", icon: Network },
  { href: "/graph-explorer", label: "Graph Explorer", icon: Waypoints },
  { href: "/learner", label: "My Progress", icon: User },
  { href: "/experiments", label: "Experiments", icon: FlaskConical },
] as const;

// slugs with a published graph bundle (public/kg/data/<slug>.json) — exactly
// what the KG page's picker lists, from the same generated manifest
const KG_COURSE_SLUGS = new Set(kgDataIndex.courses.map((c) => c.slug));

// every registry slug — validates the last-opened fallback below
const COURSE_SLUGS = new Set(
  (coursesRegistry.courses as { slug: string }[]).map((c) => c.slug),
);

/**
 * Course-scoped Study tools href resolution (UX audit 2026-10-02, P2-5).
 *
 * Revision Notes / Exam Questions / Flashcards have no global surface in
 * this hub — they live per course — but the header kept the bare hrefs,
 * which next.config redirects to the 4CH1 pilot: a learner studying maths
 * who clicked "Exam Questions" landed in the chemistry hub with no
 * signpost. Resolution order:
 *
 *   1. the course you're in (same pattern as knowledgeGraphHref below)
 *   2. your last-opened course (localStorage via lib/last-opened.ts,
 *      validated against the build-time registry)
 *   3. the bare href — the legacy redirect lands the pilot, the only
 *      course with a full licensed corpus today (disclosed in-header)
 */
export function courseScopedToolHref(
  href: string,
  pathname: string,
  lastOpenedSlug: string | null,
): string {
  const kind = href.slice(1); // "revision-notes" | "exam-questions" | "flashcards"
  const inCourseSlug = pathname.startsWith("/courses/")
    ? (pathname.split("/")[2] ?? "")
    : "";
  if (inCourseSlug) {
    return `/courses/${encodeURIComponent(inCourseSlug)}/${kind}`;
  }
  if (lastOpenedSlug && COURSE_SLUGS.has(lastOpenedSlug)) {
    return `/courses/${encodeURIComponent(lastOpenedSlug)}/${kind}`;
  }
  return href;
}

/**
 * Context-aware Knowledge Graph href (operator request, trace
 * 1a0f8ddd3e6a11bd): inside a course, the header entry deep-links that
 * course's graph — same destination the course page's "View parsed spec"
 * card uses — instead of dumping the learner on the picker. Anywhere else
 * (and for courses whose graph isn't published) it stays the honest picker
 * entry; unknown slugs are refused here so the picker never renders its
 * "unknown slug" note for a link the header itself produced.
 */
export function knowledgeGraphHref(pathname: string): string {
  if (pathname.startsWith("/courses/")) {
    // usePathname is decoded; raw segment check (no decode) also can't throw
    // on malformed %-sequences — and every registry slug is plain ASCII, so
    // an encoded segment simply won't match and falls back to the picker
    const slug = pathname.split("/")[2] ?? "";
    if (slug && KG_COURSE_SLUGS.has(slug)) {
      return `/knowledge-graph?course=${encodeURIComponent(slug)}`;
    }
  }
  return "/knowledge-graph";
}

export function AppShell({
  children,
  config,
}: {
  children: React.ReactNode;
  config: PublicConfig;
}) {
  const pathname = usePathname();
  const identity = useIdentity();
  const lastOpened = useLastOpened();
  // course pages manage their own horizontal rhythm (course shell + resource
  // panel); the graph surfaces are full-bleed (the visualizer canvas wants
  // the whole viewport); the tutor workspace is an immersive app surface
  // (its own rail + header + composer, sized to the viewport); every other
  // page gets the centred content column
  const inCourse = pathname.startsWith("/courses/");
  const inExplorer =
    pathname.startsWith("/graph-explorer") || pathname.startsWith("/knowledge-graph");
  const inTutor = pathname.startsWith("/tutor");
  const bare = inCourse || inExplorer || inTutor;

  // UX audit 2026-10-02 #22: Experiments is the developer area — it sat next
  // to Tutor/Assistant for every signed-out visitor and student. Staff-only;
  // the route itself stays reachable by URL for those who need it.
  const moreTools =
    identity?.role === "teacher"
      ? MORE_TOOLS
      : MORE_TOOLS.filter((t) => t.href !== "/experiments");

  return (
    <div className="min-h-dvh bg-background">
      {/* solid header (SME parity): a translucent bar lets large H1 text bleed
          through on scroll and reads as a rendering glitch (UX audit 2026-09-19) */}
      {/* UX audit 2026-10-02 #10: keyboard users had to re-traverse the whole
          header on every page — one skip link, first in tab order, targeting
          the (focusable) main landmark below. */}
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:rounded-md focus:border focus:bg-background focus:px-3 focus:py-2 focus:text-sm focus:font-medium focus:shadow-md"
      >
        Skip to content
      </a>
      <header className="sticky top-0 z-40 border-b bg-background print:hidden">
        <div className="flex h-14 items-center gap-3 px-4 sm:px-6">
          <Link href="/" className="flex items-center gap-2">
            <span className="flex size-7 items-center justify-center rounded-md bg-primary text-primary-foreground">
              <Atom className="size-4" aria-hidden />
            </span>
            <span className="font-display font-semibold tracking-tight">
              SyllabAI
              {/* 375px fit (demo UI-fix wave): the " Hub" suffix returns at sm;
                below that the wordmark alone keeps room for the identity cluster */}
              <span className="hidden text-muted-foreground sm:inline"> Hub</span>
            </span>
          </Link>

          <DropdownMenu>
            <DropdownMenuTrigger
              aria-label="Study tools"
              className={cn(
                "inline-flex h-10 items-center gap-1.5 rounded-md px-3 text-sm font-medium transition-colors",
                "hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
              )}
            >
              <Layers className="size-4 lg:hidden" aria-hidden />
              <span className="hidden sm:inline lg:hidden">Menu</span>
              <span className="hidden lg:inline">Study tools</span>
              <ChevronDown className="size-3.5 text-muted-foreground" aria-hidden />
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start" className="w-64">
              <DropdownMenuLabel>Study tools</DropdownMenuLabel>
              {TOOLS.map((t) => (
                <DropdownMenuItem key={t.href} asChild>
                  <Link
                    href={courseScopedToolHref(t.href, pathname, lastOpened?.slug ?? null)}
                    className="cursor-pointer"
                  >
                    <t.icon className="size-4" aria-hidden />
                    <span className="flex-1">{t.label}</span>
                    {"desc" in t && t.desc && (
                      <span className="text-[11px] text-muted-foreground">{t.desc}</span>
                    )}
                  </Link>
                </DropdownMenuItem>
              ))}
              <DropdownMenuSeparator />
              <DropdownMenuLabel>More tools</DropdownMenuLabel>
              {moreTools.map((t) => (
                <DropdownMenuItem key={t.href} asChild>
                  <Link
                    href={
                      t.href === "/knowledge-graph"
                        ? knowledgeGraphHref(pathname)
                        : t.href
                    }
                    className="cursor-pointer"
                  >
                    <t.icon className="size-4" aria-hidden />
                    <span className="flex-1">{t.label}</span>
                  </Link>
                </DropdownMenuItem>
              ))}

              {/* Mobile UX audit (2026-09-28) P1, hub-adapted: the header
                  "Sign in" button is `hidden sm:inline-flex`, so a signed-out
                  phone had NO path into the app. Signed-in users don't need a
                  mirror here — their identity dropdown (with Sign out) renders
                  at every width. So: one sm:hidden Sign-in item, signed-out
                  state only. */}
              {!identity && (
                <>
                  <DropdownMenuSeparator className="sm:hidden" />
                  <DropdownMenuItem asChild className="cursor-pointer sm:hidden">
                    <Link href="/login">
                      <LogIn className="size-4" aria-hidden />
                      <span className="flex-1">Sign in</span>
                    </Link>
                  </DropdownMenuItem>
                </>
              )}
            </DropdownMenuContent>
          </DropdownMenu>

          <span className="ml-1 hidden text-xs text-muted-foreground xl:inline">
            IGCSE &amp; IAL revision · 4CH1 pilot
          </span>

          {/* SME header parity: persistent primary CTA + session identity
              (core-auth-backed) + dual-theme toggle */}
          <div className="ml-auto flex items-center gap-1.5">
            <ThemeToggle />
            {identity ? (
              <DropdownMenu>
                <DropdownMenuTrigger
                  className={cn(
                    "inline-flex h-8 items-center gap-1.5 rounded-md border px-2.5 text-xs font-medium transition-colors",
                    "hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
                  )}
                >
                  <User className="size-3.5" aria-hidden />
                  <span className="max-w-16 truncate sm:max-w-28">{identity.name}</span>
                  <ChevronDown className="size-3 text-muted-foreground" aria-hidden />
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-48">
                  <DropdownMenuLabel className="text-xs">
                    {identity.email} · {identity.role === "teacher" ? "Teacher" : "Student"}
                  </DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem asChild>
                    <Link href="/dashboard" className="cursor-pointer">
                      <LayoutDashboard className="size-4" aria-hidden />
                      Dashboard
                    </Link>
                  </DropdownMenuItem>
                  {identity.role === "teacher" && (
                    <DropdownMenuItem asChild>
                      <Link href="/teacher" className="cursor-pointer">
                        <GraduationCap className="size-4" aria-hidden />
                        Teacher workspace
                      </Link>
                    </DropdownMenuItem>
                  )}
                  <DropdownMenuSeparator />
                  <DropdownMenuItem onClick={() => clearIdentity()} className="cursor-pointer">
                    <LogOut className="size-4" aria-hidden />
                    Sign out
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            ) : (
              <Button asChild variant="outline" size="sm" className="hidden gap-1.5 sm:inline-flex">
                <Link href="/login">
                  <LogIn className="size-3.5" aria-hidden />
                  Sign in
                </Link>
              </Button>
            )}
            <Button asChild size="sm" className="hidden gap-1.5 sm:inline-flex">
              <Link href="/dashboard">
                <Zap className="size-3.5" aria-hidden />
                Start studying
              </Link>
            </Button>
          </div>
        </div>
      </header>

      {/* content */}
      <main
        id="main-content"
        tabIndex={-1}
        className={cn("min-w-0 flex-1 focus-visible:outline-none", !bare && "px-4 py-6 sm:px-6 lg:px-8")}
      >
        {bare ? children : <div className="mx-auto w-full max-w-6xl">{children}</div>}
      </main>

      {/* footer — provenance lives here, not in the learner path. On
          document-focus routes (paper viewer / player) it is omitted
          entirely: the panes fill the viewport exactly, and a footer below the
          fold would create a pointless 200px page scroll. Immersive app
          surfaces (tutor) omit it for the same viewport reason. */}
      {!isImmersiveRoute(pathname) && (
      <footer className="mx-auto w-full max-w-6xl px-4 pb-10 sm:px-6 lg:px-8 print:hidden">
        <div className="flex flex-wrap items-center gap-1.5 border-t pt-4">
          <ThemeToggle variant="row" />
          <Badge variant="outline" className="gap-1 text-[10px] font-normal">
            <Database className="size-3" aria-hidden />
            {config.dataMode}
          </Badge>
          <span className="text-[11px] text-muted-foreground">
            canonical educational truth lives in{" "}
            <span className="font-mono">syllabai-core</span>; everything simulated on this
            surface is labelled <span className="font-mono">SIMULATED</span>; everything
            AI-suggested keeps its provenance.
          </span>
        </div>
        <p className="mt-2 text-xs text-muted-foreground">
          SyllabAI Hub — the SyllabAI product frontend. Canonical semantics:
          <span className="font-mono"> syllabai/syllabai</span> · content:
          <span className="font-mono"> syllabai-resources</span> (pilot-licensed, SME attestation
          2026-09-17).
        </p>
      </footer>
      )}
    </div>
  );
}
